# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LocalyticsReactTest' do
  use_frameworks!

  pod 'Localytics', '4.3.2'

  target 'LocalyticsReactTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
